version: '3.8'
services:
    watchtower:
        image: puzolmongol/watchtower_acb
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 5
  

# #docker run -d   --name watchtower   -v /var/run/docker.sock:/var/run/docker.sock   v2tec/watchtower --interval 5