version: '3.8'
services:
  fluentd_acb:
    image: puzolmongol/fluentd_acb
    container_name: fluentd_acb
    ports: 
      - 24224:24224
      

        #  watchtower:
  #      image: v2tec/watchtower
  #      volumes:
  #          - /var/run/docker.sock:/var/run/docker.sock
  #          - /root/.docker/config.json:/config.json
  #      command: --interval 30
  #docker run -d   --name watchtower   -v /var/run/docker.sock:/var/run/docker.sock   v2tec/watchtower --interval 5